backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Cover Image', name: 'cover_image', widget: 'image', required: false }
  - name: content
    label: Content
    files:
      - label: Resume
        name: resume
        file: "content/resume.json"
        fields:
          - { label: "Full Name", name: fullname, widget: string, required: false }
          - { label: Role, name: role, widget: string, required: false }
          - { label: Summary, name: summary, widget: text, required: false }
          - label: Experience
            name: experience
            widget: list
            required: false
            fields:
              - { label: Role, name: role, widget: string }
              - { label: Company, name: company, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: "Start date", name: start, widget: date, format: 'MM/YYYY' }
              - { label: "End date", name: end, widget: date, required: false, format: 'MM/YYYY' }
          - label: Skills
            name: skills
            widget: list
            required: false
            fields:
              - { label: Name, name: name, widget: string }